"use client"
import React, { useState } from 'react';
import "@/components/styles/time-line.scss";
import Layout from '@/components/baseLayout';
import { useTranslation } from 'react-i18next';
import { Timeline } from 'primereact/timeline';

export default function AboutUs({ params: { lng } }) {
    const { t } = useTranslation(lng, "lng", "");
    const events = [
        { date: `1911`, desc: `Дотоод хэргийг бүгд захиран шийтгэдэг яамны Төв хэлтэс нь хүн ам, малын бүртгэл мэдээг эрхлэх  чиг үүрэгтэй байжээ. Төв хэлтэс байгуулагдсаны дараа 1911 оны өвлийн сүүл сарын 25-нд аймаг хошуудад хүн амын тоо, нутаглан буй газрын хэмжээ зураг бэлтгэн ирүүлэх тухай албан бичиг хүргүүлсэн байна.  Богд Жавзандамба хутагтын буулгасан зарлигт: “Хүн ам, үнэн хөрөнгийг магадлан тоолуулах нь олон шавь боолчуудын ахуй байдлыг тунгалаг толинд үзэх адил илэрхий толилох” зорилготой болохыг тэмдэглэжээ.` },
        { date: `1918`, desc: `Хүн ам, малын тооллого явуулсан.` },
        { date: `1921`, desc: `Ардын засгийн газраас хүн ам, эд хөрөнгө, малын тооллого явуулах, улсын бүртгэл, мэдээлэл нэвтрүүлэх талаар шийдвэр гаргаж хэрэгжүүлж эхэлсэн.` },
        { date: `1961`, desc: `Анхны бүртгэлийн машинт товчоог Тоо бүртгэлийн төв газрын дэргэд байгуулсан.` },
        { date: `1962`, desc: `Анхны табулятор машин суурилуулав.` },
        { date: `1963`, desc: `Бүртгэлийн машинт товчоог станц болгож өргөтгөн зохион байгуулсан.` },
        { date: `1965`, desc: `МАХН-ын төв хороо, БНМАУ-ын Сайд нарын Зөвлөлийн 1965 оны 6 дугаар сарын 16-ны өдрийн 190/217 дугаар тогтоолоор Улаанбаатар хотод өрхийн төсвийн судалгааг нийт 230 өрх айлыг хамруулан судлах болсон. Улаанбаатар хотын статистикийн товчоонд өрхийн төсвийн 9 статистикчийн орон тоо шинээр нэмэгдсэн.` },
        { date: `1967`, desc: `Статистикийн төв байгууллага салбар хоорондын балансыг 5-10 жилийн завсарлагатай 1966, 1970, 1977, 1983, 1987 онуудаар зохиож эхэлсэн.` },
        { date: `1968`, desc: `Статистикийн төв газарт “Өрхийн төсвийн тасаг”-ийг байгуулж өрхийн төсвийн судалгааг хариуцах болов. Улаанбаатар хотын статистикийн товчооноос өрхийн судалгааны статистикчдыг шилжүүлэн авав.` },
        { date: `1971`, desc: `Статистикийн төв газарт Тооцоолон бодох төвийг байгуулав.` },
        { date: `1972`, desc: `Аж ахуйн салбаруудын нийт ба цэвэр бүтээгдэхүүнийг аймаг, Улаанбаатар хотоор жил бүр тооцдог болжээ.` },
        { date: `1974`, desc: `Тооцоолон бодох төвд Минск-32 машин суурилуулав.` },
        { date: `1975`, desc: `Статистикийн төв газар нь бүх аймагтай телетайп шугамаар холбогдох болов.` },
        { date: `1979`, desc: `Тооцоолон бодох төвд ЕС-1040 маркийн тооцоолох машин суурилуулсан.` },
        { date: `1982`, desc: `Монгол Улсаас гадаад улстай анх удаа компьютер хооронд алсын зайнд мэдээлэл солилцох боломж бүрдүүлсэн.` },
        { date: `1983`, desc: `Мэдээллийн теле боловсруулалтын Мера-100 системийг нэвтрүүлж, бүх аймгаас телефоны шугамаар синхрон модем ашиглан мэдээ авдаг болсон.` },
        { date: `1984`, desc: `Статистикийн төв газрын ажилтнууд “Оч” нэртэй микро компьютер хийв.` },
        { date: `1986`, desc: `Тооцоолон бодох төвийг ЕС-1045 маркийн тооцоолох машинаар өргөтгөн тоноглосон.` },
        { date: `1989`, desc: `Дотоодын болон үндэсний нийт бүтээгдэхүүнийг Yндэсний тооцооны системийн аргачлалаар анх удаа тооцов.` },
        { date: `1990`, desc: `Аж ахуйн нэгж, байгууллага бүрийг улсын бүртгэлд бүртгэж, регистрийн дугаар олгож, өөрчлөлт хийж эхэлсэн.` },
        { date: `1991`, desc: `Засгийн газрын 1991 оны 3-р сарын 2-ны өдрийн 71 дүгээр тогтоолоор Үндэсний тооцооны системд шилжих бэлтгэлийг хангах шийдвэр гаргав.` },
        { date: `1991`, desc: `“Сross Talk” нэртэй программ ашиглан аймгаас теле холболтоор статистикийн тоо мэдээлэл дамжуулж эхэлсэн.` },
        { date: `1991`, desc: `Үйлдвэр, аж ахуйн газар, пүүс хоршоог тоолж, таван оронтой регистрийн дугаарыг олгож, өмчийн хэлбэрээр ялган судалж эхэлсэн.` },
        { date: `1991`, desc: `Хэрэглээний бараа, үйлчилгээний үнийн индексийг Олон Улсын Валютын Сангийн аргачлалаар анх удаа тооцож эхэлсэн.` },
        { date: `1993`, desc: `НҮБ-ын Ази, номхон далайн орнуудын статистикийн институтийн гишүүнээр элссэн.` },
        { date: `1993`, desc: `Дотоодын нийт бүтээгдэхүүнийг эцсийн ашиглалтын аргаар тооцож эхэлсэн.` },
        { date: `1994`, desc: `Засгийн газрын 94-р тогтоолоор Статистикийн үзүүлэлт аргачлалыг Олон улсын стандартад нийцүүлэх зорилгоор тусгайлан хөтөлбөрийг батлуулж хэрэгжүүлсэн. /1994-1997, 2000/` },
        { date: `1994`, desc: `Аж үйлдвэрийн салбарын аж ахуйн нэгж, байгууллагын тооллогыг орон даяар зохион байгуулсан.` },
        { date: `1994`, desc: `Статистикийн тухай Монгол Улсын хууль батлагдав.` },
        { date: `1995`, desc: `"Амьжиргааны түвшний түүвэр судалгаа"-г Олон улсын нийтлэг аргачлалын дагуу анх удаа явуулсан. / 1998, 2003 онд ахин явуулсан/` },
        { date: `1996`, desc: `Хэрэглээний бараа, үйлчилгээний сагсны нэр төрлийг 205 (хуучин 123 нэр төрөл байсан) болгон нэмэгдүүлж, 1995 оны өрхийн орлого, зарлагын судалгаанаас хэрэглээний жинг шинэчлэн тооцож, 1995 оны 12 сарын үнийг суурь үе болгон хэрэглээний үнийн индексийн тооцоог шинэчилсэн.` },
        { date: `1996`, desc: `Дотоодын нийт бүтээгдэхүүнийг улсын тайлан мэдээг үндэслэн шууд тооцох аргыг практикт нэвтрүүлсэн.` },
        { date: `1997`, desc: `Аймгуудын хэрэглээний үнийн индексийг тусад нь тооцож, зарладаг болов.` },
        { date: `1997`, desc: `Албан бус секторын судалгааг анх удаа явуулсан.` },
        { date: `1998`, desc: `Төрийн байгууллагуудын анхдагч болж Статистикийн байгууллагын анхны цахим хуудсыг боловсруулж, интернэтэд байрлуулсан.` },
        { date: `1998`, desc: `Өмчийн бүх хэлбэрийн аж ахуйн нэгж, байгууллагын улсын тооллогыг явуулж, олон улсын эдийн засгийн бүх төрлийн үйл ажиллагааны салбарын ангиллыг нэвтрүүлэв.` },
        { date: `1998`, desc: `ТАСИС (Technical Assistance for the Commonwealth of Independent States) хөтөлбөрийн хүрээнд “Бизнесийн салбарын статистик, “Бизнес регистр” дэд хөтөлбөр хэрэгжиж, Үндэсний тооцооны системийн нэвтрэлтийг эрчимжүүлж эхэлсэн.` },
        { date: `1998`, desc: `НҮБ-ын Хүнс хөдөө аж ахуйн байгууллагын тусламжтай “Малын ашиг шим гарцын судалгаа”, “ХАА-н бүтээгдэхүүний өртөг, зардлын судалгаа”, “ХАА-н бүтээгдэхүүний үйлдвэрлэгчийн үнийн судалгаа”-г 8 аймагт анх уда зохион байгуулсан.` },
        { date: `1998`, desc: `“Хүн амын нөхөн үржихүйн эрүүл мэнд” түүвэр судалгаа явуулсан.` },
        { date: `1998`, desc: `Нийслэл хотын “Хүн ам” мэдээллийн санг байгуулав. Засаг захиргааны анхан шатны нэгжид хөтөлдөг хүн ам, өрхийн бүртгэлийг статистикийн зорилгоор ашиглах эхлэл болов.` },
        { date: `1999`, desc: `“Бизнес регистрийн санд баяжилт, хөдөлгөөн хийх, мэдээлэх журам”-ыг баталж, Бизнес регистрийн мэдээг аж ахуйн нэгж, байгууллагуудаас теле холболтоор улирал бүр авдаг болсон.` },
        { date: `2000`, desc: `Аж үйлдвэрийн статистикийн салбарт түүвэр судалгааны аргыг нэвтрүүлэв.` },
        { date: `2000`, desc: `Улсын төсвийн статистикийн мэдээллийг Сангийн яамнаас албан ёсоор авч, тархааж эхэлсэн.` },
        { date: `2000`, desc: `Дотоодын нийт бүтээгдэхүүнийг аймгийн түвшинд тооцож эхэлсэн.` },
        { date: `2000`, desc: `Хүн ам, өрхийн захиргааны бүртгэлээр улсын хэмжээнд аймаг, хот, сум, дүүрэг, баг, хорооны түвшинд “Хүн ам, өрхийн мэдээллийн сан” байгуулж, албан ёсны статистикийн үйл ажиллагаанд ашиглаж эхэлсэн.` },
        { date: `2001`, desc: `Улаанбаатар хотын хэрэглээний сагсны нэр төрлийг 239, аймгуудын хэрэглээний сагсны нэр төрлийг 139 болгон нэмэгдүүлж, хэрэглээний жинг шинэчлэн, индексийг Ласпейрсийн хувиргасан индексээр 2000 оны 12-р сарыг суурь үе болгон тооцож эхэлсэн.` },
        { date: `2001`, desc: `Бизнес регистрийн мэдээлэлд үндэслэн статистикийн түүвэр судалгааг аж үйлдвэр, худалдаа, зоогийн газар гэсэн салбаруудад явуулж эхэлсэн.` },
        { date: `2001`, desc: `Үндэсний татварын ерөнхий газрын татвар төлөгчийн мэдээллийн санд үндэслэн аж ахуйн нэгж, байгууллагын борлуулалтын орлогын мэдээллийг бизнес регистрийн санд тусгадаг болсон.` },
        { date: `2001`, desc: `Yндэсний тооцооны системийн голлох 6 дансыг байгуулсан.` },
        { date: `2002`, desc: `Дотоод худалдаа, зочид буудал, зоогийн газар зэрэг үйлчилгээний салбарын статистикийн мэдээллийг албан ёсоор нийтэд тархааж эхэлсэн.` },
        { date: `2002`, desc: `Хөдөөгийн хөгжлийг жендерийн мэдрэмжтэй болгоход чиглэгдсэн судалгаа явуулсан.` },
        { date: `2002`, desc: `Цаг ашиглалтын туршилт судалгааг явуулав.` },
        { date: `2002`, desc: `Азийн хөгжлийн банкны техник, санхүүгийн тусламжтайгаар ажиллах хүчин болон хүүхдийн хөдөлмөрийн хавсарга түүвэр судалгаа хийсэн.` },
        { date: `2003`, desc: `Дотоод худалдаа, зочид буудал, зоогийн газар, авто тээврийн салбарт албан бус секторын судалгааг явуулсан.` },
        { date: `2003`, desc: `Бизнес регистрийн сангийн үзүүлэлтийг статистикийн хэрэглэгчдэд тархааж эхэлсэн.` },
        { date: `2004`, desc: `Албан ёсны болон захиргааны статистикийн үзүүлэлтийг хянан, олон улсын стандарт аргачлалд нийцүүлж, мэдээллийн тогтолцоог боловсронгуй болгосон.` },
        { date: `2004`, desc: `Тахир дутуу иргэдийн нэг удаагийн бүртгэлийн түүвэр судалгааг явуулсан.` },
        { date: `2005`, desc: `Дэлхийн банкны “Малын индексжүүлсэн даатгал” төслийн хүрээнд мал аж ахуйн салбарт түүвэр судалгааны аргыг нэвтрүүлэх туршилтыг 4 аймагт явууллаа.` },
        { date: `2005`, desc: `Хэрэглээний сагсны нэр төрлийг 294 болгон нэмэгдүүлж, хэрэглээний жинг Өрхийн орлого, зарлагын судалгааны 2005 оны дүнгээр шинэчлэн, индексийг 2005 оны 12-р сарыг суурь үе болгон тооцов.` },
        { date: `2006`, desc: `Албан ёсны статистикийг 2006-2010 онд хөгжүүлэх анхны хөтөлбөрийг УИХ-аар батлуулав.` },
        { date: `2006`, desc: `Хэрэглээний үнийн улсын индексийг тооцох аргачлалыг шинэчилж, улсын индексийг аймаг, нийслэлийн өрхийн хэрэглээний зардлаар жигнэсэн дундаж үзүүлэлтээр тооцдог болсон.` },
        { date: `2006`, desc: `“Аж ахуйн нэгж, байгууллагын тооллого”-г зохион байгуулж, Монгол Улсад үйл ажиллагаа явуулахаар бүртгүүлсэн өмчийн бүх хэлбэрийн хуулийн этгээд, тэдгээрийн салбар нэгж болон хувиараа хөдөлмөр эрхлэгчдийг тооллогод хамруулж, мэдээллийг бизнес регистрийн санд тусгаснаар 2005 оны суурьтай Нөөц ашиглалтын хүснэгт, Салбар хоорондын тэнцлийг байгуулах боломж бүрдсэн.` },
        { date: `2006`, desc: `Малын ашиг шим гарцын судалгаа, Хөдөө аж ахуйн бүтээгдэхүүний өртөг зардлын судалгаа, Хөдөө аж ахуйн бүтээгдэхүүний үйлдвэрлэгчийн үнийн судалгааг 8 аймагт зохион байгуулж явуулсан.` },
        { date: `2007`, desc: `Аж ахуйн нэгж, байгууллагын 2006 оны тооллогын дүнд үндэслэн Бизнес регистрийн сангийн бүтцийг өөрчилж, аж ахуйн нэгж, байгууллагыг олон үйл ажиллагаагаар бүртгэх боломжийг бүрдүүлсэн.` },
        { date: `2007`, desc: `Үйлдвэрлэгчийн үнийн индексийг тооцох аргачлалыг бий болгон, туршилтаар тооцож эхлэв.` },
        { date: `2008`, desc: `УИХ-аас албан ёсны статистикийн төв байгууллагын статусыг Статистикийн хороо болгох шийдвэр гаргаж, Статистикийн тухай хуульд нэмэлт өөрчлөлт оруулав.` },
        { date: `2008`, desc: `Хүн ам, орон сууцны улсын тооллогын тухай Монгол Улсын хууль батлагдав.` },
        { date: `2008`, desc: `Орон сууцны үнийн индекс тооцох аргачлалыг батлуулж, тооцож эхлэв.` },
        { date: `2008`, desc: `Жижиглэн худалдааны үнийн индекс, Барилгын өртгийн индекс тооцох аргачлалыг боловсруулж, индексийг туршилтаар тооцож эхэлсэн.` },
        { date: `2008`, desc: `Дотоод худалдааны салбарын албан бус секторын судалгааг Ажиллах хүчний судалгааны хавсарга судалгаа болгон дангаар нь явуулсан.` },
        { date: `2009`, desc: `Бизнес регистрийн санд “Эдийн засгийн бүх төрлийн үйл ажиллагааны 4.0 хувилбар”, ‘’Эдийн засгийн секторын ангилал’’-ыг нэвтрүүлсэн.` },
        { date: `2009`, desc: `Хүнсний аюулгүй байдлын статистикийн үзүүлэлтүүдийг тодорхойлж, өрх, улсын түвшинд хүнсний аюулгүй байдлын статистикийн үзүүлэлтүүдийг тооцох анхны аргачлалыг батлав.` },
        { date: `2010`, desc: `Хүн ам, орон сууцны ээлжит тооллогын хүрээнд гадаадад суугаа Монгол Улсын иргэдийг анх удаа интернэтээр тоолов.` },
        { date: `2010`, desc: `Албан бус секторын судалгааг хөдөө аж ахуйгаас бусад эдийн салбарын үйл ажиллагаанд зохион байгуулав.` },
        { date: `2010`, desc: `Бизнес регистрийн санд Монгол Улсын бүсчилсэн код (ZIP CODE)-ыг нэвтрүүлснээр аж ахуйн нэгж, байгууллагын хаягжилтыг аймаг, нийслэл, сум, дүүрэг, баг, хороо, байршлаар шалгах боломж бүрдсэн.` },
        { date: `2010`, desc: `Хэрэглээний сагсны нэр төрлийг 329 болгон нэмэгдүүлж, хэрэглээний жинг шинэчлэн тооцов.` },
        { date: `2011`, desc: `Албан ёсны статистикийг 2011-2015 онд хөгжүүлэх хоёр дахь хөтөлбөрийг УИХ-аар батлуулав.` },
        { date: `2011`, desc: `Аж ахуйн нэгж, байгууллагын улсын ээлжит тооллогыг зохион байгуулав. Монгол Улсад үйл ажиллагаа явуулахаар бүртгүүлсэн өмчийн бүх хэлбэрийн хуулийн этгээд, тэдгээрийн салбар нэгжийг тооллогод хамруулж, аж ахуйн нэгж, байгууллагын газар зүйн мэдээллийн санг анх удаа байгуулсан.` },
        { date: `2012`, desc: `Хөдөө аж ахуйн улсын анхдугаар тооллогыг зохион байгуулав.` },
        { date: `2012`, desc: `Мал тооллогын онлайн системийг нэвтрүүлж, өрх, аж ахуйн нэгж байгууллага бүрээр анхан шатны мэдээллийн баазыг бий болгосон.` },
        { date: `2012`, desc: `“Байгалийн нөөцөд суурилсан эдийн засгийн статистик” Улаанбаатар хотын группийг байгуулсан.` },
        { date: `2012`, desc: `Эдийн засгийн салбаруудын статистикийн мэдээлэл боловсруулалтыг засаг захиргаа, нутаг дэвсгэрийн анхан шатны нэгжээр бүрдүүлж эхлэв.` },
        { date: `2012`, desc: `Швейцарын Хөгжлийн Агентлагийн “Тогтвортой бичил уурхай” төслийн дэмжлэгээр Бичил уурхай эрхлэгчдийн судалгааг анх удаа явууллаа.` },
        { date: `2013`, desc: `Хүн амын тооллогын олон улсын XXVI бага хурлыг Улаанбаатар хотноо зохион байгуулав.` },
        { date: `2013`, desc: `Нөөц ашиглалтын хүснэгт, Салбар хоорондын балансыг 2010 оны гүйцэтгэлд суурилан байгуулж, дүн шинжилгээ хийв.` },
        { date: `2013`, desc: `Статистикийн мэдээллийн нэгдсэн сан (www.1212.mn)-ыг ашиглалтад оруулав.` },
        { date: `2013`, desc: `Бизнес регистрийн нэгдсэн мэдээллийн санг олон улсын стандартад нийцүүлэн сайжруулав. Энэ нь сүлжээний орчинд серверт байрласан, статистик нэгжийн тулгуурласан, албан ёсны статистикийн мэдээллийг ачаалах, засвар, өөрчлөлтийг тусгах, ашиглах, үр дүн гаргах цогц программ хангамжтай болсон.` },
        { date: `2013`, desc: `Нийгэм, эдийн засгийн салбаруудын нэмэгдэл өртгийг тооцоонд ашиглах жилийн мэдээний нэгдсэн стандарт маягтыг бий болгож, нэгдсэн онлайн программаар цуглуулж, боловсруулж эхэлсэн.` },
        { date: `2013`, desc: `Хүүхэд хөгжил, Нөхөн үржихүйн эрүүл мэнд болон Хүн амын эрүүл мэндийн судалгааг нэгтгэн “Нийгмийн үзүүлэлтийн судалгаа” нэртэйгээр зохион байгуулсан.` },
        { date: `2013`, desc: `Мэдээлэл цуглуулалтад орчин үеийн техникийн дэвшил болох таблет төхөөрөмжийг ашиглаж эхэлсэн.` },
        { date: `2014`, desc: `ҮСХ, Нийслэлийн статистикийн газар, 21 аймаг, 9 дүүргийн статистикийн хэлтсүүдийг холбосон мэдээллийн нэгдсэн сүлжээг бий болгов.` },
        { date: `2014`, desc: `Монгол Улсын 21 аймаг, нийслэлийн “Статистикийн товчоон” ном хэвлэгдэн гарлаа.` },
        { date: `2014`, desc: `Монгол Улсын үндэсний статистикийн системд олон улсын үнэлгээний багаар анх удаа цогц үнэлгээг хийлгэв.` },
        { date: `2014`, desc: `Албан ёсны үйл ажиллагаа эрхэлж буй статистикийн байгууллагыг Монгол Улсын төрийн дээд шагнал ”Хөдөлмөрийн гавьяаны улаан тугийн одон”-гоор шагнав.` },
        { date: `2015`, desc: `Монгол Улсын 3 сая дахь иргэнийг тодруулав.` },
        { date: `2014`, desc: `“Хүн ам өрхийн мэдээллийн сан”-г онлайн болгож, УБЕГ-ын бүртгэлийг холбосон.` },
        { date: `2015`, desc: `Төрийн байгууллагуудад бий болсон мэдээллийн санг судалж, ашиглах, уялдуулах ажлыг эхлүүлж, УБЕГ-ын Иргэний мэдээллийн санг Хүн ам, өрхийн мэдээллийн санд өөрчлөлт орсон тухай бүрд нь баталгаажуулах, Боловсрол, Эрүүл мэнд, Нийгмийн даатгал, Нийгмийн халамж, Иргэний харьяат шилжих хөдөлгөөний сан, Иргэний мэдээллийн сангуудыг Хүн ам, өрхийн мэдээллийн сантай, Хуулийн этгээдийн санг статистикийн Бизнес регистрийн сантай тулгалт хийж, тэдгээрийг холбох, уялдуулах ажлуудыг эхэлсэн.` },
        { date: `2015`, desc: `Хүн ам, орон сууцны 2015 оны завсрын тооллогыг анх удаа зохион байгууллаа.` },
        { date: `2015`, desc: `Хагас жилийн малын түүвэр судалгааг явуулж эхэллээ.` },
        { date: `2015`, desc: `Малын ашиг шим, ХАА-н бүтээгдэхүүний өртөг, зардлын судалгаа, Хөдөө аж ахуйн бүтээгдэхүүний үйлдвэрлэгчийн үнийн судалгааг улсын хэмжээнд зохион байгуулав.` },
        { date: `2015`, desc: `Хэрэглээний үнийн индексийг сумын түвшинд тооцох арга зүйг боловсруулав. Арга зүйн дагуу нийт 112 сумаас үнийн мэдээллийг сар бүр цуглуулан авч, аймгийн үнийн индексийг тооцдог болов.` },
        { date: `2016`, desc: `“Аж ахуйн нэгж, байгууллагын улсын ээлжит тооллого”-г анх удаа бүртгэлд суурилсан аргыг уламжлалт аргатай хослуулан зохион байгуулсан.` },
        { date: `2016`, desc: `Салбар хоорондын тэнцэл, Нөөц, ашиглалтын хүснэгтийн 2015 оны суурь судалгааг зохион байгууллаа.` },
        { date: `2016`, desc: `ХБНГУ-ын Холбооны статистикийн газартай Хосолмол түншлэлийн хамтын ажиллагааны хэлэлцээрийн хүрээнд "Чадавхыг бэхжүүлэх" бичил төслийн гэрээ байгуулав.` },
        { date: `2017`, desc: `Монгол Улсын статистикийн салбарыг 2017-2020 онд хөгжүүлэх үндэсний гурав дахь хөтөлбөрийг УИХ-аар батлуулав.` },
        { date: `2017`, desc: `Статистикийн мэдээллийг нэг дороос шуурхай авах MonStat болон EzStat аппликейшныг 1212.mn нэртэйгээр шинэчлэн гаргав.` },
        { date: `2017`, desc: `"Тогтвортой хөгжил - Статистик" үндэсний чуулганыг зохион байгуулав.` },
        { date: `2017`, desc: `Үндсэн хуулийн өөрчлөлтөд зориулсан Зөвлөлдөх санал асуулгыг зохион байгуулж, үр дүнг танилцуулав.` },
        { date: `2017`, desc: `Хүн амын 2045 он хүртэл хэтийн тооцоог боловсруулав.` },
        { date: `2017`, desc: `Хэрэглээний үнийн индексийг 2015 суурьт шилжүүлэн үндсэн 12 бүлгийн дагуу 373 (Улаанбаатар хотод 344, аймгуудад 238 нэр төрөл) нэр төрлийн бараа, үйлчилгээгээр тооцож, дундаж үнийг тооцохдоо геометр дундаж ашиглах болсон.` },
        { date: `2017`, desc: `Үйлчилгээний салбарын (Тээвэр, мэдээлэл холбоо, зочид буудал, нийтийн хоол, бөөний болон жижиглэн худалдаа) үйлдвэрлэгчийн үнийн индексийг тооцон тархаах болов.` },
        { date: `2017`, desc: `Статистикийн мета мэдээллийн санг хүн ам, нийгэм, эдийн засгийн салбарууд болон макро эдийн засгийн үзүүлэлтүүдээр бүрдүүлж, шинэчлэн сайжруулав.` },
        { date: `2017`, desc: `Швейцарын Хөгжлийн Агентлагийн “Тогтвортой бичил уурхай” төслийн дэмжлэгтэйгээр Бичил уурхай эрхлэгчдийн судалгааг 19 аймаг, Налайх дүүрэгт зохион байгуулж, үр дүнг тархаасан.` },
        { date: `2017`, desc: `Финландын Статистикийн газартай Харилцан Ойлголцлын Санамж бичиг байгуулав.` },
        { date: `2017`, desc: `“Эрчим хүчний үйлдвэрлэл, хэрэглээ” судалгааг зохион байгуулсан.` },
        { date: `2018`, desc: `"21 дүгээр зууны Статистикийн Хөгжлийн Төлөөх Түншлэл" Консорциумын (ПАРИС21) -ийн Удирдах зөвлөлд гишүүнээр элсэв.` },
        { date: `2018`, desc: `Америк, Ази, Номхон Далайн орнуудын Үндэсний тооллого, Статистикийн байгууллагын дарга нарын нийгэмлэг (ANCSDAAP)-ийн Ерөнхийлөгчөөр сонгогдов.` },
        { date: `2018`, desc: `Унгарын Статистикийн төв газартай Харилцан ойлголцлын санамж бичиг байгуулав.` },
        { date: `2018`, desc: `“Бизнес регистрийн үйлдвэрлэгчийн чанарын тайлан”, “Аж ахуйн нэгж, байгууллагын 2016 оны тооллогын хэрэглэгчийн чанарын тайлан”, “Бизнес регистрийн хэрэглэгчийн чанарын тайлан”-г тус тус боловсруулж, чанарын удирдлагын механизмыг нэвтрүүлсэн.` },
        { date: `2018`, desc: `Олон улсад мөрдөж буй аргачлал, гарын авлагыг үндэслэн “Бизнес регистрийг байгуулах, хөтлөх түр аргачлал”-ыг сайжруулж, батлуулсан.` },
        { date: `2018`, desc: `УБЕГ-ын хуулийн этгээдийн мэдээллийн санг Бизнес регистрийн мэдээллийн сантай уялдуулж, шинээр байгуулагдсан, татан буугдсан, өөрчлөгдсөн аж ахуйн нэгж, байгууллагын мэдээллийг тухай бүр бизнес регистрийн санд тусгах боломжийг бүрдүүлсэн программ хангамжийг нэвтрүүлсэн.` },
        { date: `2018`, desc: `Эдийн засгийн статистикийн салбарын сар, улирлын мэдээг томоохон аж ахуйн нэгж байгууллагаас вебд суурилсан онлайн программаар цуглуулж эхэлсэн.` },
        { date: `2018`, desc: `Материалын урсгалын данс, Эрчим хүчний биет урсгалын данс, Байгаль орчны татварын дансыг 2015, 2016 оноор байгуулсан.` },
        { date: `2018`, desc: `Жендерт суурилсан хүчирхийлэл судалгааг зохион байгуулав.` },
        { date: `2018`, desc: `Азийн Хөгжлийн Банктай хамтран “Хөрөнгийн эзэмшлийг хүйсээр тодорхойлох нь” туршилтын судалгааг хийв.` },
        { date: `2018`, desc: `Эрүүл Мэндийн Яам болон Улсын бүртгэлийн ерөнхий газартай хамтран шинээр төрсөн хүүхдийг нийслэлийн бүх шатлалын эмнэлэг болон аймгийн төрөх эмнэлэгт цахимаар бүртгэж эхэлсэн.` },
        { date: `2018`, desc: `Боловсролын хүрээлэнтэй хамтран EБС-ийн 1-11-р ангийн сурагчдын математик, статистикийн мэдлэг, чадварыг хөгжүүлэх “Статистикийн арга зүйн гарын авлага”-ыг гаргаж, 798 сургуульд хүргүүлсэн. НҮБ-ын Статистикийн комисс болон олон улсын бусад байгууллагаас гарын авлагыг бусад улс оронд нэвтрүүлэхийг уриалж сайшаасан.` },
        { date: `2018`, desc: `Тогтвортой хөгжлийн зорилгын хэрэгжилтийг хянах, үнэлэх хяналтыг систем (dashboard)-ыг байгуулав.` },
        { date: `2019`, desc: `“Тогтвортой хөгжлийн зорилго-2030”-ын хөтөлбөрийг хэрэгжүүлэхэд статистикийн түншлэл, хамтын ажиллагаа, удирдлага зохион байгуулалтаар хангах, чадавхыг бэхжүүлэхэд дэмжлэг үзүүлэх үүрэг бүхий Дээд түвшний бүлгийн 14 дэх удаагийн уулзалтыг Улаанбаатар хотноо зохион байгуулав.` },
        { date: `2019`, desc: `“Тогтвортой хөгжлийн зорилго-2030” хөтөлбөрийг хэрэгжүүлэхэд статистикийн түншлэл, хамтын ажиллагаа, удирдлага зохион байгуулалтаар хангах, чадавхыг бэхжүүлэхэд дэмжлэг үзүүлэх үүрэг бүхий Дээд түвшний бүлгийн даргаар сонгогдов.` },
        { date: `2019`, desc: `Бүгд Найрамдах Казахстан Улсын Үндэсний эдийн засгийн яамны Статистикийн Хороотой Харилцан ойлголцлын санамж бичиг байгуулав.` },
        { date: `2019`, desc: `21 дүгээр зууны Статистикийн хөгжлийн төлөөх түншлэл (ПАРИС21)-ийн удирдах зөвлөлийн даргаар сонгогдов.` },
        { date: `2019`, desc: `Монгол Улсын Үндэсний Статистикийн Хороо НҮБ-ын Ази, Номхон далайн орнуудын статистикийн институтийн Удирдах зөвлөлийн гишүүнээр сонгогдов.` },
        { date: `2019`, desc: `НҮБ-ын Хүн амын сантай хамтран Ази, Номхон далайн бүсийн 11 улсын статистикийн албан хаагчдыг оролцуулсан “Тооллогод төхөөрөмж ашиглах нь” ахисан түвшний бүсийн семинарыг Улаанбаатар хотноо зохион байгуулав.` },
        { date: `2019`, desc: `Байшин, орон сууцны 2019 оны тооллогыг хаягийн зураг ашиглан байршилд суурилсан хэлбэрээр явуулж, мэдээллийг зөөврийн төхөөрөмж, Collector for ArcGIS, Survey123 for ArcGIS программыг ашиглан цуглуулсан.` },
        { date: `2019`, desc: `Байгаль орчин, эдийн засгийн нэгдсэн дансны Материалын урсгалын дансыг 2005-2018 оноор, Байгаль орчны татварын дансыг 2015-2018 оноор тус тус байгуулав.` },
        { date: `2019`, desc: `“Жендэрийн мэдрэмжтэй төрийн байгууллага”-аар өргөмжлөгдөв.` },
        { date: `2019`, desc: `Цаг ашиглалтын судалгааны мэдээлэл цуглуулахад анх удаа Survey1212 mobile app ашиглаж, судалгааны өдрийн тэмдэглэл хөтлөв.` },
        { date: `2019`, desc: `Өгөгдөл дүрслэлийн Tableau программ нэвтрүүлж, интерактив дашбоард хийж эхэлсэн.` },
        { date: `2019`, desc: `Олон Улсын Валютын Сангийн Мэдээлэл тархаалтын тусгай стандарт (SDDS)-д бүрэн шилжиж, энэ стандартыг нэвтрүүлсэн дэлхийн 76 орны нэг боллоо.` },
        { date: `2019`, desc: `Азийн хөгжлийн банк, Байгаль орчин, аялал жуулчлалын яамтай хамтран “Байгаль орчны статистикийг хөгжүүлэх үндсэн хүрээ-FDES-2013”, “Байгаль орчин, эдийн засгийн данс-SEEA”, “Ногоон хөгжлийн бодлого”, Байгаль орчны яамны хэрэгцээ шаардлага, үзүүлэлтийг тооцох боломж зэрэгт үндэслэн байгаль орчны статистик мэдээллийн 7 багц бүхий 18 маягт, “Байгаль орчны статистикийн үзүүлэлтийг тооцох аргачлал”-ыг шинэчлэн боловсруулсан.` },
        { date: `2019`, desc: `Дотоод худалдааны салбарын (2021) статистикийн мэдээг их өгөгдлийг (НӨАТУС) ашиглаж, сараар гарган тархааж эхлэв.` },
        { date: `2020`, desc: `Хүн ам, орон сууцны 2020 оны улсын ээлжит тооллогыг хосолмол аргаар зохион байгууллаа. Монгол Улсын нийт өрхийн 10 хувийг энгийн санамсаргүй түүврийн аргаар сонгож, тоологч биечлэн очиж, 90 хувийг төрийн байгууллагуудын мэдээллийн сантай “Хүн ам, өрхийн мэдээллийн сан”-г тулган уялдуулж, шинэчлэн баяжуулж тоолсон.` },
        { date: `2020`, desc: `НҮБ-ын Ази, Номхон Далайн орнуудын Эдийн Засаг, Нийгмийн Комиссын Статистикийн хорооны товчооны 2020-2022 оны гишүүнээр сонгогдсон.` },
        { date: `2020`, desc: `Open Data Watch байгууллагаас улс, орнуудын статистикийн байгууллагын мэдээллийн нээлттэй байдлын ODIN 2020/21 үнэлгээгээр 187 орноос Монгол Улс 9 дүгээр байрт, Азийн орнуудаас 1 дүгээр байранд шалгарсан.` },
        { date: `2020`, desc: `Статистикийн мэдээллийг Татварын ерөнхий газар, Гааль, татварын статистикийн мэдээллийн технологийн төвийн НӨАТУС-ийн мэдээлэлтэй уялдуулах программ хангамжийг хөгжүүлэв.` },
        { date: `2020`, desc: `Үндэсний тооцооны Хөрөнгийн биет хэмжээний бусад өөрчлөлтийн данс, Хөрөнгийн дахин үнэлгээний дансыг байгуулав.` },
        { date: `2020`, desc: `Дуудлагын төв (Call center)-ийг байгуулж, утсаар судалгаа явуулж эхлэв.` },
        { date: `2020`, desc: `Хүн амын тооллогын 30 дугаар бага хурлыг цахимаар зохион байгуулсан.` },
        { date: `2021`, desc: `Монгол Улс – 100 жилд эмхэтгэлийг боловсруулан гаргав.` },
        { date: `2021`, desc: `“Төрийн их өгөгдлийг бодлогын шийдвэрт ашиглах нь” төслийн хэлэлцүүлгийг Монгол Улсын Ерөнхийлөгчийн ивээл дор Төрийн ордонд зохион байгуулсан.` },
        { date: `2021`, desc: `Статистикийн мэдээлэл боловсруулах систем (SPS)-ийг нэвтрүүлэв.` },
        { date: `2021`, desc: `Ази-Номхон далайн орнуудын Хөдөө аж ахуйн статистикийн комиссын 29 дүгээр хурлыг Улаанбаатар хотод анх удаа зохион байгуулав.` },
        { date: `2021`, desc: `Тогтвортой хөгжлийн зорилгын шалгуур үзүүлэлтийн Бүс дундын шинжээчдийн бүлэг (IAEG-SDG)-ийн 2021- 2023 онд Зүүн Азийг төлөөлөх гишүүнээр Бодлого, хамтын ажиллагааны газрын Бодлого, гадаад харилцааны хэлтсийн дарга сонгогдлоо.` },
        { date: `2021`, desc: `Дэлхийн банкны Ухаалаг засаг төслийн хүрээнд газар тариалангийн статистик мэдээлэлд алсын зайнаас тандан судлах арга зүйг ашиглан тариалалтыг ургамлын төрлөөр ангилах туршилтыг хийв.` },
        { date: `2022`, desc: `Аж ахуйн нэгж, байгууллагын тооллогыг цахимаар зохион байгуулж, анх удаа хувиараа хөдөлмөр эрхлэгчдийг тоолж, инновацын тухай мэдээллийг цуглуулсан.` },
        { date: `2022`, desc: `НҮБ-ын АНДЭЗНК-ын Статистикийн Хорооны VIII хурлын даргаар ҮСХ-ны дарга сонгогдов.` },
        { date: `2022`, desc: `Хөдөө аж ахуйн 2022 оны ээлжит улсын тооллогыг газар зүйн мэдээллийн системтэй уялдуулан зохион байгуулав.` },
        { date: `2022`, desc: `Хэрэглээний үнийн сагс, жинг 6 дахь удаагаа шинэчилж, 2020 оны суурьт шилжүүлэв.` },
        { date: `2022`, desc: `“Олон улсын өртгийн зэрэгцүүлэлтийн-2020” хөтөлбөрийг амжилттай хэрэгжүүлж, дуусгав.` },
        { date: `2022`, desc: `Анхдагч мэдээллийн чанарыг сайжруулах ажлын хүрээнд статистикийн мэдээллийн сан, түүвэр судалгааны мэдээлэл цуглуулах, тархаах үзүүлэлтүүдийн уялдааг хангахад мөрдөх багц журмуудыг шинэчлэн батлав.` },
        { date: `2022`, desc: `ҮСХ-ны албан ёсны цахим хуудас, албан ёсны статистикийн мэдээллийн нэгдсэн санг шинэчлэн сайжруулав.` },
        { date: `2022`, desc: `Үндсэн хуулийн 30 жилийн ойн эмхэтгэлийг 1989-2020 оноор бэлтгэж, тархаасан.` }
    ];

    const events_en = [
        { date: `1911`, desc: `All of the Ministry Centralian Department of Department is punished by all the Department of Department has been dutied. After the Central Department was submitted a letter of the 1911 Winter Demands in 1911 Wrastal Garisms, the amounts of a landscape of the 1911 in the 1911 Winter and Top Footal Post. Bulkandambbbbbbba Unloaded Principal Principal: "Counting the populations and true mirroredness" the population "siblings"` },
        { date: `1918`, desc: `Sent population and animal counts.` },
        { date: `1921`, desc: `The Parkdown started to make a decision to make a decision or personal records or information to introduce national records and information.` },
        { date: `1961`, desc: `The first log machine has been established in the center of the number of the number of numbers.` },
        { date: `1962`, desc: `The original tabulator car was installed.` },
        { date: `1963`, desc: `The log machine has been expanded to the station.` },
        { date: `1965`, desc: `Mass Central Committee, 1965 Council 1965 Council 1965 Council 1965 Council Council 317 Housebound Purchases 317 Housebound Housebound Studies of Housebound Studies in Rs.16 Ministers 16. Ulaanabar Statistics Statistical Bureau Budget's Budget's 9 statistics' publicly added.` },
        { date: `1967`, desc: `Statistics Center Balance Started with 5-10 years in 1966, 1970, 1970, 1970, 1970, 1977, 1970, 1977, 1977, 1983, 1983, 1983, 1983)` },
        { date: `1968`, desc: `Forming the "household budget) to establish the" household budget survey) Moved Household Research Statistics of Household Survey Bureau.` },
        { date: `1971`, desc: `Established the center of calculation to the center of Statistics.` },
        { date: `1972`, desc: `Total and net product has been calculated every year in province and Ulaanorous city.` },
        { date: `1974`, desc: `Minsk-32 cars were installed in the calculator.` },
        { date: `1975`, desc: `Statistics Center to contact a teleport line with all provincials.` },
        { date: `1979`, desc: `Mounted nine-1040 Mark calculating cars in Computarization Center.` },
        { date: `1982`, desc: `Mongolia took a chance to exchange information between the first time in a computer for the first time in a computer.` },
        { date: `1983`, desc: `The information telephonization of the Data Telephonization Mera-100 System has been introduced using synchronous modems and from Telephonic Tracks from Telephone Line.` },
        { date: `1984`, desc: `Statistical center staff made a micro computer named "Spark"` },
        { date: `1986`, desc: `Estimate equipped with calculating center of estimates of Estimators.` },
        { date: `1989`, desc: `The gross and national and national product was first calculated by the method of billing system.` },
        { date: `1990`, desc: `Each enterprise or organization is recorded in state registration and issued the registration number and started making changes.` },
        { date: `1991`, desc: `The government has been decided to meet the resolution to a National billing system to be moved by 71 March 1991.` },
        { date: `1991`, desc: `A statistical number of statistical numbers were started with a Tele connection using "Saint Talk"` },
        { date: `1991`, desc: `Factory, a firm and firm count and start the five-digit registry number and began to explore the five-digit mode.` },
        { date: `1991`, desc: `The Price Index has begun to account for the first time in the International Currency Treasury methods.` },
        { date: `1993`, desc: `Joined the statistics member of the United Nations and Pacific countries.` },
        { date: `1993`, desc: `The gross domestic product has begun to be calculated by the final use method.` },
        { date: `1994`, desc: `Statistical Indicator to Government 94 statistical statements were submitted to the program specifically to meet international standards. / 1994-1997, 2000 /` },
        { date: `1994`, desc: `Industrial industry or organization's census was held around the country.` },
        { date: `1994`, desc: `Statistical statistics confirmed.` },
        { date: `1995`, desc: `"Sammer-level sample research" as the first time in international common methodology. / 1998 and sent again in 2003 /` },
        { date: `1996`, desc: `Increased use of consumer goods and services of use of use of use of use of use of use of use of use of use of use of use of use of use of use of use of use in 1995)` },
        { date: `1996`, desc: `Intended publicity of the country of local returns directly to the state of the country's reports were introduced.` },
        { date: `1997`, desc: `The Price Index index separated and announced separately.` },
        { date: `1997`, desc: `The informal sector study was first sent.` },
        { date: `1998`, desc: `Procratically processed the first e-mail to the first e-mail of statistical institutions of government agencies.` },
        { date: `1998`, desc: `Census of all forms of property and organizations of all forms and organizations were introduced to all international economic industries.` },
        { date: `1998`, desc: `Tasis (Technical Assistance for the Commonwealth States' Stats' statistics'` },
        { date: `1998`, desc: `United Nations Food Surveyed "Equipment Survey" and "Cost Survey", "Product Price Study," Product Price Study "and" Calm Product Survey "and" Close-National Product Survey "` },
        { date: `1998`, desc: `"Population reproductive health" sample survey.` },
        { date: `1998`, desc: `Established the "population" database of the capital. The population and household records are to be used for the use of statistical for statistical purposes.` },
        { date: `1999`, desc: `"Regarding and Registered Profile in Business Registry Funds" and reports business registers from enterprise or organizations.` },
        { date: `2000`, desc: `The method of sample research methods in Industry Statistics.` },
        { date: `2000`, desc: `Statists of national budget statistics are officially taken from the Ministry of Treasury.` },
        { date: `2000`, desc: `The gross domestic product has begun to account at the province level.` },
        { date: `2000`, desc: `The population or household administration has been established in national states, city, or in a city, a city, a mountaintop, or in a district or hostile statistical activity.` },
        { date: `2001`, desc: `Mounts Capital Use Basket Payments 239 and Ages December Type Competition Basket Retrieved and December's December Type December 2000 in Lasplays Constitution.` },
        { date: `2001`, desc: `Statistical sample surveyed on the basis of business registers, starting in industry and restaurants.` },
        { date: `2001`, desc: `National Tax General Tax Tax and Organization Sales Sales Sales Sales Sales Revenue Income Requested Income Property Requests of Business Registration.` },
        { date: `2001`, desc: `Built up 6 accounts of the main billing systems of the billing system.` },
        { date: `2002`, desc: `The statistics of services included in a formal public details of service and restaurants and restaurants.` },
        { date: `2002`, desc: `Conducted a course oriented survey to make a rural development with gender sensitivity.` },
        { date: `2002`, desc: `Time use tests sent out.` },
        { date: `2002`, desc: `A sample of Asian Development Bank Techniques and Carrier Sampled Sample Research.` },
        { date: `2003`, desc: `Carried informal sector studies in internal trade, restaurants, restaurants and auto.` },
        { date: `2003`, desc: `Business Register Foundation Started Statistical Users Spread Statistical Users.` },
        { date: `2004`, desc: `Formal and administrative statistics to be met and concluded to a system of information systems.` },
        { date: `2004`, desc: `Carried out a one-time-of-time sample survey survey.` },
        { date: `2005`, desc: `Sent the test of the World Bank "Industrial Insurance Approaches to introduce a test of the sample survey to introduce a sample survey.` },
        { date: `2005`, desc: `Increase applied basket dignity, 2005 to the 2005 and expeditual earnings and expenses of use as a background period of 2005.` },
        { date: `2006`, desc: `The formal statistics were approved to develop first program in 2006-2010.` },
        { date: `2006`, desc: `Consuming Price Index has been updated to considered methods of calculating the method of calculating and the state index has been calculated by steamed average in provincial or capital uses.` },
        { date: `2006`, desc: `Organize "Enterprise or Organization Census" and the equivalent of all-sector laws and the equivalent reserves and self-employed reserves and the equivalent residence composed of the creation of the form.` },
        { date: `2006`, desc: `The cost of animal's benefit, agricultural costs and agricultural goods research and agricultural product survey was held in 8 provinces.` },
        { date: `2007`, desc: `Based on the 2006 Census of 2006 Business Registers, and created a business register or organization to record enterprise or organizations.` },
        { date: `2007`, desc: `As a manufacturer price index as a method of consideration, began to account for a test.` },
        { date: `2008`, desc: `Official Statistics Central Statistics Center Center Decision to make statistical commodity to Statistics Committee to Statistical Committee to Statistical Committee.` },
        { date: `2008`, desc: `Approved Mongolian law of population and housing country.` },
        { date: `2008`, desc: `The housing price index was approved and began to account for.` },
        { date: `2008`, desc: `Retail price index and construction index processed to be processed and started to account for the index testing.` },
        { date: `2008`, desc: `Sent individually as a survey of internal shopping sector study as a survey survey.` },
        { date: `2009`, desc: `The "Economic Operations" in the Registry Fund of "Economic Operation" 'Economic Sector Sector Category' - x.` },
        { date: `2009`, desc: `Identify food security statistics and confirmed the first method of calculating food safety statistics.` },
        { date: `2010`, desc: `Counts abroad for the first time international to the internalities of the population or apartment count` },
        { date: `2010`, desc: `An informal Sector survey was held in an economy other than agriculture.` },
        { date: `2010`, desc: `Intermittent code (ZIP CODE) in the Regional Retention Code (ZIP CODE), including Article, Organization, District, Team, Team, Team, Committee to check.` },
        { date: `2010`, desc: `Computer basket dignity increased 329 and revised the weight of consumption.` },
        { date: `2011`, desc: `The formal statistics were approved with the Second Program to Develop a Second Program 2011-2015.` },
        { date: `2011`, desc: `Organized counts of enterprise and organizations. Census of all forms of property recorded in the Mongolia for the first time to censor the entire field of law, including the Census and Organization Department of Enterprise.` },
        { date: `2012`, desc: `Organized Census of the Agricultural State.` },
        { date: `2012`, desc: `The veterinary system has been introduced online systems and created primary database in each household and enterprise.` },
        { date: `2012`, desc: `"Economic Stats-based economic statistics" Marked City Group has been established.` },
        { date: `2012`, desc: `Statistical information of economic sectors have begun to form the Processing of the Processing of Administration and Territory.` },
        { date: `2012`, desc: `Switzerland Development Agency "Steady Micro-Messer Survey Survey for the first time.` },
        { date: `2013`, desc: `The population census international xxvi has arranged for his taxarial conference.` },
        { date: `2013`, desc: `Resources Table and Branch Balance established and analyzed in 2010 performance in 2010 performance.` },
        { date: `2013`, desc: `The United States Information Funds (www.1212.mn) to be used.` },
        { date: `2013`, desc: `The business register of the registration has been improved in matching international standards. It has been a complex program to boot or use the network environments, reflected, reflection or use of formal statistics or changes to reflect, use or results` },
        { date: `2013`, desc: `Created an united states of news to the annual news of an annual news to the estimate of the Community Sorts of Social and Economic Sectory.` },
        { date: `2013`, desc: `Baby has been held in a "Social health study" Social Professional Research "` },
        { date: `2013`, desc: `Information started using tablet equipment to be modern techniques.` },
        { date: `2014`, desc: `Holds, capital statistics, 21 provinces, 21 provincial stats, 9 Districted statistics networks.` },
        { date: `2014`, desc: `Mongolian 21 Statistical Bureau 'Statistics' Bureau' books have been published.` },
        { date: `2014`, desc: `Mongolian national statistics for the first time for international assessment teams for the first time.` },
        { date: `2014`, desc: `The Mongolian Rwards of Statistical Square 'Labor Turns' Labor Turns 'for Mongolian State Prize'` },
        { date: `2015`, desc: `Mongolia identifies citizen in 3 million.` },
        { date: `2014`, desc: `"Population Deposit" online to the Ubeg account and Ubeg accounts.` },
        { date: `2015`, desc: `Started and used to explore the database to explore and use the database in government facility, and social welfare or social welfare Citizens databases have a statistical account of a lifetime and lawyer in a lawyer of a lawyer and a legal business register of statistical business register.` },
        { date: `2015`, desc: `The population and housing 2015 has been held for the first time.` },
        { date: `2015`, desc: `The sample of a half annual animal sample has begun.` },
        { date: `2015`, desc: `The cost of animal's benefit and costs, costs and expenses producer's producer's procedurer's procedurer's priced staff.` },
        { date: `2015`, desc: `Competition price index has been processed to account for arrow levels. Methodological Due to a total of 112 arrows in total 112 arrows took place monthly and accounted for the province value index.` },
        { date: `2016`, desc: `"Edgree and Organization Census" in a combination of accounts in combination with traditional methods with traditional ways.` },
        { date: `2016`, desc: `Between sector balance, resources, resources and utility spreadsheets were arranged.` },
        { date: `2016`, desc: `Fixed 'micro project agreement "to strengthen the ability" in combinations of combinations with the Federal Statistics Department of Herm Union.` },
        { date: `2017`, desc: `Mongolian Statistics Branch has been approved by 2017-2020` },
        { date: `2017`, desc: `Statistics released to the prompts Monstat and EZSTAT and EZSTAT app to be updated with 1212.mn 1212.mn.` },
        { date: `2017`, desc: `"Steady development - Statistics' National Assault.` },
        { date: `2017`, desc: `Organizing consultation questions for the constitutional change and introduced the result.` },
        { date: `2017`, desc: `Developed overheads until 2045 of the population.` },
        { date: `2017`, desc: `The use of consumer prices index is credited with 373 (238 nouns) in 373 (238 nouns) in order to be based on the 373 (238 etcs)` },
        { date: `2017`, desc: `Service branch (a transport, information, or wholesal) producing index of a manufacturer price index.` },
        { date: `2017`, desc: `Statistical Meta database has been formed with a population, social, economy or macro economy.` },
        { date: `2017`, desc: `Swiss Development agency 'steadygirls' study of Micro-Messer "projects 'steady miniers' study with a micro-micro-mine support, the micro-mine survey was held in 19 provinces and nalales.` },
        { date: `2017`, desc: `The Finnish Memorandum has been established with a mutual confoundation with the Statistics place.` },
        { date: `2017`, desc: `"Energy production and use" survey has been held.` },
        { date: `2018`, desc: `"21 Partnerships for the 21 Cierce Statistical Development Partnage" joined a member of the Board (Paris21)` },
        { date: `2018`, desc: `National Certificate of National Citations of America and Pacific and Pacific Country Community Community (ANCSDAAP) was selected.` },
        { date: `2018`, desc: `The Hungary Statistics Memorandum has been established with mutual position.` },
        { date: `2018`, desc: `"Business Registry Manufacturer Profile Report" Entertainment Customer Customer Customer Customer Customer Customer Customer Customer Customer Customer Customer Customer Customer Customer Customer Customer Customer Customer Customer Customer Mechanism).` },
        { date: `2018`, desc: `Improved and approved "Business Registration" and maintained business registers "based on internationally` },
        { date: `2018`, desc: `Approximated by the Uband Legal Database of Business Register, Each Approved, Displaced Negotiated, Disclosed, Displaced Entry and Organization Funds.` },
        { date: `2018`, desc: `Economic Statistical Sector Morty News and Seasons starting from a large enterprise of the season to be collected in a major entity program.` },
        { date: `2018`, desc: `Materials of material flow accounts and energy-body-lights, Environmental Tax Accounts were established in 2015 and 2016 and 2016.` },
        { date: `2018`, desc: `Genders-based violence organized a survey.` },
        { date: `2018`, desc: `Collaborate with Asian Development Bank "is to" define a test survey.` },
        { date: `2018`, desc: `A newly born child with the Ministry of Health and State Registry Started Electronic Highborhood Hospital and Provincial Houseborn Hospital.` },
        { date: `2018`, desc: `Development "statistical methodological guidelines" to develop a Mathematical Knowledge of the Ebs 1-11 Grades, Statics, Statics Guidelines and Skilled to Schools. The UN Said Comment from Comments Commission and other other local organizations to introduce a guide to other country.` },
        { date: `2018`, desc: `The system of controlling and evaluation of a stable Development of the implementation (DashBoard)` },
        { date: `2019`, desc: `The "State Development Goal-2030" has been held in the Upstick Partner and Administration, Administration, Administration, Administration, Administration, Administration, Administration, Administration and Administration or Commodity Holds to Keep Competition.` },
        { date: `2019`, desc: `"Sustained Development Goal-2030" Participate, Administration, Administration, Administration, Administration, Administration, Administration, Administration, Administration, Administration, Administration, Computer Chairman.` },
        { date: `2019`, desc: `Republican National Ministry of Casakhstan established a Memorial Memorial Memorandum with the statistical committee.` },
        { date: `2019`, desc: `21 Comparing Statistical Development Partists (Paris21) were selected by the Board of the board of board.` },
        { date: `2019`, desc: `Mongolian Statistics Committee was elected as a member of the statistics of the statistics of the United Nations and Pacifics of Asia and Pacific Countries.` },
        { date: `2019`, desc: `Competitions involved in "Censolic officials with 11th Pacific Status Officers with the United Nations Pacific Staters and Pacific Status Area.` },
        { date: `2019`, desc: `Collection of 2019 Census of House and Home-based forms using locations, data-based devices and COLLECTOR FOR ARCGIS, SurcGis, SurcGis, Surcgis programs.` },
        { date: `2019`, desc: `Environmental and economy united accounts of Materials Travel Accounts 2005-2018 for 2005-2018, Environmental Tax accounts in 2015-2018.` },
        { date: `2019`, desc: `Exalted with "Gender sensitivity".` },
        { date: `2019`, desc: `Time use Research information was used for Survey1212 Mobile App for the first time Survey App and the survey notes.` },
        { date: `2019`, desc: `The data representative tableau programmed and started doing interactive Dashboar.` },
        { date: `2019`, desc: `International Currency information is fully transferred to Spread Special Standard (SDDS) and one of the 76ths of the world introduced this standard.` },
        { date: `2019`, desc: `Asian Development Bank, Environmental Statistics, "Environmental Statistics," Environmental Account Sept, Economic Account-SEEA "," Green Development Policy) 18 forms with 7 forms of environmental statistics and "Methodistical stats of statistical statistical statistics" based on the degree.` },
        { date: `2019`, desc: `The internal shopping industry (2021) statistical news (VATUT) began to use great data and spread the moon.` },
        { date: `2020`, desc: `The population and accommodation of the 2020 perched 2020 perchedness census is hosted in combination. Mongolian State Total Households and Counts Personal Samples and Counts Intercented and Counts Really Counts 'Datarians'` },
        { date: `2020`, desc: `The United Nations Asia and Pacific Committee, Social Comment Statistical Committee Committee 2020-2022 to 2020-2022.` },
        { date: `2020`, desc: `OPEN DATA WATA WATTERS ATTENTION IN 187 COUNTRY 1820/21 in exchange for Josts and 1 in Asian countries.` },
        { date: `2020`, desc: `Statistical data developed to be released to the Customs General Tax and Tax Status Center.` },
        { date: `2020`, desc: `Established other changes accounts and assessment accounts of the physical billing of national billing.` },
        { date: `2020`, desc: `Call Center (Call Center) and started on the phone survey.` },
        { date: `2020`, desc: `Electronically organized a Low Conference 30 of the population Census.` },
        { date: `2021`, desc: `THE MOBILE - Draft the compilation in 100 years.` },
        { date: `2021`, desc: `"The use of State Data for Policy Details" Project Discussion was held at the Police Palace under the President's President.` },
        { date: `2021`, desc: `Statistical information processing system (SPS) were introduced.` },
        { date: `2021`, desc: `Asian-Pacific Status Committed Statistics Comments 29 for the first time in the Ulbarian Commission Commissioner for the first time.` },
        { date: `2021`, desc: `A stable Development Temperature Crust of Temperature Temperature Competition Area (IaEG-SDG), 2021- East Associate Policy Creating Chief of Foreign Department of Level, 2023.` },
        { date: `2021`, desc: `The cultivation tested to explored remote statistics in the scope of the world's wise Governments, the cultivation is made by scoring remote.` },
        { date: `2022`, desc: `Electronic Entry and Organization Census has been electronically organized and collected the first self-employed information.` },
        { date: `2022`, desc: `The UN's Andenk's Statistics Committee Viii Chief Chairman was elected.` },
        { date: `2022`, desc: `Census of 2022 Agricultural State Census were organized with a geographical information system.` },
        { date: `2022`, desc: `Updated use basket and weight 6 in 6th due and transferred to the base of 2020.` },
        { date: `2022`, desc: `"International Reality-2020" program has been successfully completed and completed.` },
        { date: `2022`, desc: `Authorized statistics procedures are updated to collect the statistical database and sample reports to collect and sample data to enhance data survey data.` },
        { date: `2022`, desc: `Upgraded to the United King of Official E-Page and Official Statistics Information Foundation.` },
        { date: `2022`, desc: `Prepared 30th anniversary of the constitution in 1989-2020 and spreads.` }
    ];

    const timelineEvents = lng === "mn" ? events : events_en;

    return (
        <Layout lng={lng}>
            <br />
            <div className='nso_main_section'>
                <div className="nso_about_us_body">
                    <div className="nso_container">
                        <div>
                            <div className="__timeline_title">
                                {lng === "mn" ? "Он цагийн түүхэн товчоо" : "History of Mongolian Statistics"}
                            </div>
                            <div className="card">
                                <Timeline
                                    value={timelineEvents}
                                    opposite={(event) => (
                                        <span className='opposite'>
                                            {event.date}
                                        </span>
                                    )}  // Date on opposite side
                                    marker={() => (
                                        <div className="__middlecircle">
                                            <i className="pi pi-angle-down"></i>  {/* Custom marker */}
                                        </div>
                                    )}
                                    content={(event) => (
                                        <small className="p-text-secondary" style={{ width: "600px", display: 'block' }}>
                                            {event.desc}
                                            <br />
                                        </small>
                                    )}
                                />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </Layout>
    );
}
