import type { IntroDashboardConfig } from "@/lib/statcate-intro/types";

const YOY = "DT_NSO_0600_010V1.px";
const BASE = { "Суурь он": ["2"] };

export const consumerPriceIndex: IntroDashboardConfig = {
  id: "consumer-price-index",
  subsector: "Consumer Price Index",
  title: { mn: "Хэрэглээний үнэ", en: "Consumer price index" },
  subtitle: { mn: "инфляц, бүлэг, аймаг", en: "inflation, groups, aimags" },
  palette: ["#1A5CAD", "#0E7C7B", "#2980B9", "#5B6B80"],
  mapColors: ["#E8F1F8", "#A8C8E0", "#5B9BC4", "#1A5CAD", "#0D3A66"],
  dimensions: { time: "Он", geo: "Бүс" },
  tables: [
    {
      id: "headline",
      file: YOY,
      time: "Сар",
      label: { mn: "Инфляц, өмнөх оны мөн үе", en: "Inflation, year-on-year" },
      icon: "cpi",
      format: "percent",
      select: { ...BASE, Бүлэг: ["0"] },
    },
    {
      id: "food",
      file: YOY,
      time: "Сар",
      label: { mn: "Хүнсний үнэ", en: "Food prices" },
      icon: "food",
      format: "percent",
      select: { ...BASE, Бүлэг: ["1"] },
    },
    {
      id: "housing",
      file: YOY,
      time: "Сар",
      label: { mn: "Орон сууц, түлш", en: "Housing and fuels" },
      icon: "housing",
      format: "percent",
      select: { ...BASE, Бүлэг: ["4"] },
    },
    {
      id: "yearEnd",
      file: "DT_NSO_0600_013V2.px",
      label: { mn: "Инфляц, оны эцэст", en: "Inflation, year-end" },
      icon: "calendar",
      format: "percent",
      select: { Үзүүлэлт: ["0"] },
    },
    {
      id: "groups",
      file: YOY,
      time: "Сар",
      label: { mn: "Бүлгээр, өмнөх оны мөн үе", en: "By group, year-on-year" },
      format: "percent",
      select: BASE,
    },
    {
      id: "aimag",
      file: "DT_NSO_0303_07V8.px",
      time: "Сар",
      geo: "Бүс",
      label: { mn: "ХҮИ, өмнөх оны мөн үе", en: "CPI, year-on-year" },
      format: "percent",
      select: { ...BASE, Бүлэг: ["0"] },
    },
  ],
  widgets: [
    { type: "kpis", tables: ["headline", "food", "housing", "yearEnd"] },
    {
      type: "category-bars",
      table: "groups",
      dimension: "Бүлэг",
      layout: "horizontal",
      span: "full",
      totals: ["Ерөнхий индекс"],
      labelMap: {
        "Хүнсний бараа, ундаа, ус": "Хүнс",
        "Согтууруулах ундаа, тамхи": "Ундаа, тамхи",
        "Хувцас бөс бараа, гутал": "Хувцас, гутал",
        "Орон сууц, ус, цахилгаан, түлш": "Орон сууц, түлш",
        "Гэр ахуйн тавилга, гэр ахуйн бараа": "Гэр ахуй",
        "Эм, тариа эмнэлгийн үйлчилгээ": "Эм, эмнэлэг",
        "Холбооны хэрэгсэл, шуудангийн үйлчилгээ": "Холбоо",
        "Амралт, чөлөөт цаг, соёлын бараа, үйлчилгээ": "Амралт, соёл",
        "Боловсролын үйлчилгээ": "Боловсрол",
        "Зочид буудал, зоогийн газар, дотуур байр": "Зочид буудал, хоол",
        "Даатгал, санхүүгийн үйлчилгээ": "Даатгал, санхүү",
        "Бусад бараа, үйлчилгээ": "Бусад",
      },
      title: { mn: "Инфляц, бараа үйлчилгээний бүлгээр", en: "Inflation by COICOP group" },
    },
    {
      type: "region-map",
      table: "aimag",
      layout: { legend: "horizontal" },
    },
    {
      type: "region-bars",
      table: "aimag",
      title: { mn: "Инфляц, аймаг, нийслэлээр", en: "Inflation by aimag" },
    },
    {
      type: "trend",
      tables: ["headline"],
      yAxis: "nice",
      span: "full",
      height: 280,
      title: { mn: "Инфляц, өмнөх оны мөн үетэй", en: "Year-on-year inflation" },
    },
  ],
};
