import type { IntroDashboardConfig } from "@/lib/statcate-intro/types";

export const environmentalEconomicAccount: IntroDashboardConfig = {
  id: "environmental-economic-account",
  subsector: "Environmental-Economic Account",
  title: {
    mn: "Байгаль орчин – эдийн засгийн данс",
    en: "Environmental-economic accounts",
  },
  subtitle: { mn: "зардал, татвар, эрчим хүч", en: "expenditure, taxes, energy" },
  palette: ["#0E7C7B", "#2E7D32", "#1A5CAD", "#5B6B80"],
  dimensions: { time: "Он" },
  tables: [
    {
      id: "protection",
      file: "DT_NSO_2023_001V3.px",
      label: { mn: "Байгаль хамгааллын зардал", en: "Environmental protection expenditure" },
      unit: { mn: "сая ₮", en: "million ₮" },
      icon: "protection",
      format: "currency",
      select: { Зардал: ["0"] },
    },
    {
      id: "tax",
      file: "DT_NSO_3600_002V1.px",
      label: { mn: "Байгаль орчны татвар", en: "Environmental taxes" },
      unit: { mn: "сая ₮", en: "million ₮" },
      icon: "tax",
      format: "currency",
      select: { "Татварын төрөл": ["0"], "Эдийн засгийн салбар": ["0"] },
    },
    {
      id: "energy",
      file: "DT_NSO_3600_005V1.px",
      label: { mn: "Эрчим хүчний нийт нийлүүлэлт", en: "Total energy supply" },
      unit: { mn: "ТЖ", en: "TJ" },
      icon: "energy",
      format: "decimal",
      select: { Үзүүлэлт: ["0"], Бүтээгдэхүүн: ["0"] },
    },
    {
      id: "protectionTypes",
      file: "DT_NSO_2023_001V3.px",
      label: { mn: "Хамгааллын зардал, төрлөөр", en: "Protection expenditure by type" },
      unit: { mn: "сая ₮", en: "million ₮" },
      format: "currency",
      select: { Зардал: ["1", "2", "3", "4"] },
    },
    {
      id: "energyProducts",
      file: "DT_NSO_3600_005V1.px",
      label: { mn: "Эрчим хүч, бүтээгдэхүүнээр", en: "Energy supply by product" },
      unit: { mn: "ТЖ", en: "TJ" },
      format: "decimal",
      select: { Үзүүлэлт: ["0"] },
    },
  ],
  widgets: [
    { type: "kpis", tables: ["protection", "tax", "energy"] },
    {
      type: "category-stats",
      table: "protectionTypes",
      dimension: "Зардал",
      title: { mn: "Байгаль хамгааллын зардал, төрлөөр", en: "Protection expenditure by type" },
    },
    { type: "trend", tables: ["protection", "tax"], yAxis: "fromZero", title: { mn: "Зардал, татвар", en: "Expenditure and tax" } },
    {
      type: "category-bars",
      table: "energyProducts",
      dimension: "Бүтээгдэхүүн",
      layout: "horizontal",
      top: 8,
      totals: ["Бүгд"],
      labelMap: {
        "Нүүрснээс гаргаж авсан брикет, шахмал нүүрс болон эдгээртэй төстэй хатуу түлш": "Брикет, шахмал нүүрс",
        "Автобензин (био түлшийг оруулахгүй)": "Автобензин",
        "Бусад нефтийн болон тосон бүтээгдэхүүн": "Бусад нефть",
        "Нефтийн вазелин, парафины лав, байгалийн битум болон асфальт": "Вазелин, битум",
        "Мод, модны хаягдал болон бусад биомасс, модны нүүрс": "Биомасс",
        "Цахилгаан эрчим хүч": "Цахилгаан",
        "Kокс болон хагас кокс": "Кокс",
      },
      title: { mn: "Эрчим хүчний нийлүүлэлт, бүтээгдэхүүнээр", en: "Energy supply by product" },
    },
  ],
};
