import type { IntroDashboardConfig } from "@/lib/statcate-intro/types";

export const investment: IntroDashboardConfig = {
  id: "investment",
  subsector: "Investment",
  title: { mn: "Хөрөнгө оруулалт", en: "Investment" },
  subtitle: { mn: "дотоод, гадаад, Шууд хөрөнгө оруулалт", en: "domestic, foreign, FDI" },
  palette: ["#1A5CAD", "#0E7C7B", "#8E44AD", "#C0392B"],
  mapColors: ["#E3F2FD", "#90CAF9", "#42A5F5", "#1A5CAD", "#0D47A1"],
  dimensions: { time: "Он", geo: "Бүс" },
  tables: [
    {
      id: "total",
      file: "DT_NSO_0901_001V1.px",
      label: { mn: "Нийт хөрөнгө оруулалт", en: "Total investment" },
      unit: { mn: "сая ₮", en: "million ₮" },
      icon: "investment",
      format: "currency",
      select: { "Хөрөнгө оруулалтын төрөл": ["0"] },
    },
    {
      id: "domestic",
      file: "DT_NSO_0901_001V1.px",
      label: { mn: "Дотоодын хөрөнгө оруулалт", en: "Domestic investment" },
      unit: { mn: "сая ₮", en: "million ₮" },
      icon: "domestic",
      format: "currency",
      select: { "Хөрөнгө оруулалтын төрөл": ["1"] },
    },
    {
      id: "foreign",
      file: "DT_NSO_0901_001V1.px",
      label: { mn: "Гадаадын хөрөнгө оруулалт", en: "Foreign investment" },
      unit: { mn: "сая ₮", en: "million ₮" },
      icon: "foreign",
      format: "currency",
      select: { "Хөрөнгө оруулалтын төрөл": ["2"] },
    },
    {
      id: "fdi",
      file: "DT_NSO_1500_004V4_1.px",
      label: { mn: "ГШХО-ын орох урсгал", en: "FDI inflow" },
      unit: { mn: "сая $", en: "million $" },
      icon: "fdi",
      format: "decimal",
      select: { "Хөрөнгө оруулагч улс": ["0"] },
    },
    {
      id: "fdiCountries",
      file: "DT_NSO_1500_004V4_1.px",
      label: { mn: "ГШХО, улсаар", en: "FDI by country" },
      unit: { mn: "сая $", en: "million $" },
      format: "decimal",
    },
    {
      id: "bySector",
      file: "DT_NSO_0901_002V1.px",
      label: { mn: "Хөрөнгө оруулалт, салбараар", en: "Investment by industry" },
      unit: { mn: "сая ₮", en: "million ₮" },
      format: "currency",
    },
    {
      id: "stateBudget",
      file: "DT_NSO_0901_004V1.px",
      geo: "Бүс",
      label: { mn: "Улсын төсвийн хөрөнгө оруулалт", en: "State budget investment" },
      unit: { mn: "сая ₮", en: "million ₮" },
      format: "currency",
    },
  ],
  widgets: [
    { type: "kpis", tables: ["total", "domestic", "foreign", "fdi"] },
    { type: "trend", tables: ["total", "domestic", "foreign"], yAxis: "fromZero", span: "full", height: 280, title: { mn: "Хөрөнгө оруулалт, эх үүсвэрээр", en: "Investment by source" } },
    {
      type: "category-bars",
      table: "bySector",
      dimension: "Эдийн засгийн салбар",
      layout: "horizontal",
      top: 8,
      totals: ["Бүгд"],
      labelMap: {
        "Хөдөө аж ахуй, ойн аж ахуй, загас барилт, ан агнуур": "Хөдөө аж ахуй",
        "Цахилгаан, хий, уур, агааржуулалт, усан хангамж": "Цахилгаан, ус",
        "Бөөний болон жижиглэн худалдаа, машин, мотоциклийн засвар, үйлчилгээ": "Худалдаа",
        "Тээвэр ба агуулахын үйл ажиллагаа": "Тээвэр",
        "Зочид буудал, байр, сууц болон нийтийн хоолны үйлчилгээ": "Зочид буудал, хоол",
        "Санхүүгийн болон даатгалын үйл ажиллагаа": "Санхүү, даатгал",
        "Үл хөдлөх хөрөнгийн үйл ажиллагаа": "Үл хөдлөх хөрөнгө",
        "Төрийн удирдлага ба батлан хамгаалах үйл ажиллагаа, албан журмын нийгмийн хамгаалал": "Төрийн удирдлага",
        "Хүний эрүүл мэнд ба нийгмийн үйл ажиллагаа": "Эрүүл мэнд",
        "Үйлчилгээний бусад үйл ажиллагаа": "Бусад үйлчилгээ",
      },
      title: { mn: "Хөрөнгө оруулалт, салбараар", en: "Investment by industry" },
    },
    {
      type: "region-map",
      table: "stateBudget",
      layout: { legend: "horizontal" },
    },
    {
      type: "category-bars",
      table: "fdiCountries",
      dimension: "Хөрөнгө оруулагч улс",
      layout: "horizontal",
      span: "full",
      top: 8,
      totals: ["Нийт"],
      title: { mn: "ГШХО-ын орох урсгал, улсаар", en: "FDI inflow by country" },
    },
  ],
};
