import type { IntroDashboardConfig } from "@/lib/statcate-intro/types";

export const moneyAndFinance: IntroDashboardConfig = {
  id: "money-and-finance",
  subsector: "Money and Finance",
  title: { mn: "Мөнгө, санхүү", en: "Money and finance" },
  subtitle: { mn: "M2, ханш, зээл, хадгаламж", en: "M2, exchange rate, loans, deposits" },
  palette: ["#1A5CAD", "#B8860B", "#0E7C7B", "#C0392B"],
  mapColors: ["#E8F0FA", "#9BB8DC", "#4A7FB5", "#1A5CAD", "#0D3B73"],
  dimensions: { time: "Он", geo: "Бүс" },
  tables: [
    {
      id: "m2",
      file: "DT_NSO_0700_001V2.px",
      time: "Сар",
      label: { mn: "Мөнгө M2", en: "Money supply M2" },
      unit: { mn: "тэрбум ₮", en: "billion ₮" },
      icon: "money",
      format: "decimal",
      select: { Үзүүлэлт: ["0"] },
    },
    {
      id: "usd",
      file: "DT_NSO_0700_008V1.px",
      time: "Сар",
      label: { mn: "АНУ-ын доллар", en: "US dollar" },
      unit: { mn: "₮ / $", en: "₮ / $" },
      icon: "fx",
      format: "decimal",
      select: { Валют: ["2"] },
    },
    {
      id: "loans",
      file: "DT_NSO_0700_002V2.px",
      time: "Сар",
      label: { mn: "Зээлийн үлдэгдэл", en: "Outstanding loans" },
      unit: { mn: "сая ₮", en: "million ₮" },
      icon: "loans",
      format: "currency",
      select: { "Зээлийн ангилал": ["0"], Салбараар: ["0"] },
    },
    {
      id: "npl",
      file: "DT_NSO_0700_002V2.px",
      time: "Сар",
      label: { mn: "Чанаргүй зээл", en: "Non-performing loans" },
      unit: { mn: "сая ₮", en: "million ₮" },
      icon: "npl",
      format: "currency",
      select: { "Зээлийн ангилал": ["3"], Салбараар: ["0"] },
    },
    {
      id: "loanQuality",
      file: "DT_NSO_0700_002V2.px",
      time: "Сар",
      label: { mn: "Зээлийн чанар", en: "Loan quality" },
      unit: { mn: "сая ₮", en: "million ₮" },
      format: "currency",
      select: { "Зээлийн ангилал": ["1", "2", "3"], Салбараар: ["0"] },
    },
    {
      id: "citizenLoans",
      file: "DT_NSO_0700_031V1.px",
      time: "Сар",
      label: { mn: "Иргэдийн зээл, төрлөөр", en: "Household loans by type" },
      unit: { mn: "тэрбум ₮", en: "billion ₮" },
      format: "decimal",
    },
    {
      id: "deposits",
      file: "DT_NSO_0700_006V1.px",
      geo: "Бүс",
      label: { mn: "Иргэдийн хадгаламж", en: "Household deposits" },
      unit: { mn: "сая ₮", en: "million ₮" },
      format: "currency",
    },
  ],
  widgets: [
    { type: "kpis", tables: ["m2", "usd", "loans", "npl"] },
    {
      type: "category-stats",
      table: "loanQuality",
      dimension: "Зээлийн ангилал",
      title: { mn: "Зээлийн чанар", en: "Loan quality" },
    },
    { type: "trend", tables: ["m2"], yAxis: "fromZero", title: { mn: "Мөнгө M2", en: "Money supply M2" } },
    { type: "trend", tables: ["usd"], yAxis: "nice", title: { mn: "АНУ-ын долларын ханш", en: "USD exchange rate" } },
    {
      type: "category-bars",
      table: "citizenLoans",
      dimension: "Үзүүлэлт",
      layout: "horizontal",
      totals: ["Бүгд"],
      labelMap: {
        "Эдийн засгийн үйл ажиллагаа эрхлэх зээл": "Бизнесийн зээл",
        "Хадгаламж, данс барьцаалсан зээл": "Барьцаат зээл",
        "Өрхийн хэрэглээний зээл": "Өрхийн хэрэглээ",
      },
      title: { mn: "Иргэдэд олгосон зээл, төрлөөр", en: "Household loans by type" },
    },
    {
      type: "region-map",
      table: "deposits",
      layout: { legend: "horizontal" },
    },
  ],
};
