import type { IntroDashboardConfig } from "@/lib/statcate-intro/types";

const SECTOR_LABELS = {
  "Хөдөө аж ахуй, ойн аж ахуй, загас барилт, ан агнуур": "Хөдөө аж ахуй",
  "Цахилгаан, хий, уур, агааржуулалтын хангамж": "Цахилгаан, хий, уур",
  "Усан хангамж; бохир ус, хог, хаягдлын менежмент болон цэвэрлэх үйл ажиллагаа": "Усан хангамж",
  "Бөөний болон жижиглэн худалдаа, машин, мотоциклийн засвар, үйлчилгээ": "Худалдаа",
  "Тээвэр ба агуулахын үйл ажиллагаа": "Тээвэр",
  "Зочид буудал, байр, сууц болон нийтийн хоолны үйлчилгээ": "Зочид буудал, хоол",
  "Санхүүгийн болон даатгалын үйл ажиллагаа": "Санхүү, даатгал",
  "Үл хөдлөх хөрөнгийн үйл ажиллагаа": "Үл хөдлөх хөрөнгө",
  "Мэргэжлийн, шинжлэх ухаан болон техникийн үйл ажиллагаа": "Мэргэжлийн, ШУ",
  "Удирдлагын болон дэмжлэг үзүүлэх үйл ажиллагаа": "Удирдлагын дэмжлэг",
  "Төрийн удирдлага ба батлан хамгаалах үйл ажиллагаа, албан журмын нийгмийн хамгаалал": "Төрийн удирдлага",
  "Хүний эрүүл мэнд ба нийгмийн үйл ажиллагаа": "Эрүүл мэнд",
  "Урлаг, үзвэр, тоглоом, наадам": "Урлаг, үзвэр",
};

const USE_LABELS = {
  "Өрхийн хэрэглээ, Өрхөд үйлчилдэг ашгийн бус байгууллагын хэрэглээ": "Өрхийн хэрэглээ",
  "Төрийн байгууллагын хэрэглээ": "Төрийн хэрэглээ",
  "Үндсэн хөрөнгийн хуримтлал": "Үндсэн хөрөнгө",
  "Цэвэр экспорт": "Цэвэр экспорт",
};

export const nationalAccounts: IntroDashboardConfig = {
  id: "national-accounts",
  subsector: "National Accounts",
  title: { mn: "Үндэсний тооцоо", en: "National accounts" },
  subtitle: { mn: "ДНБ, өсөлт, нэг хүнд ногдох", en: "GDP, growth, per capita" },
  palette: ["#1A5CAD", "#0E7C7B", "#C0392B", "#5B6B80"],
  mapColors: ["#E3F2FD", "#90CAF9", "#42A5F5", "#1A5CAD", "#0D47A1"],
  dimensions: { time: "Он", geo: "Бүс" },
  tables: [
    {
      id: "gdp",
      file: "DT_NSO_0500_003V1_annual.px",
      label: { mn: "ДНБ, оны үнээр", en: "GDP, current prices" },
      unit: { mn: "сая ₮", en: "million ₮" },
      icon: "gdp",
      format: "currency",
      select: { Үзүүлэлт: ["0"], Бүрэлдэхүүн: ["0"] },
    },
    {
      id: "growth",
      file: "DT_NSO_0500_003V1_annual.px",
      label: { mn: "Эдийн засгийн өсөлт", en: "Economic growth" },
      icon: "growth",
      format: "percent",
      select: { Үзүүлэлт: ["4"], Бүрэлдэхүүн: ["0"] },
    },
    {
      id: "perCapita",
      file: "DT_NSO_0500_010V1.px",
      label: { mn: "Нэг хүнд ногдох ДНБ", en: "GDP per capita" },
      unit: { mn: "мян. ₮", en: "thousand ₮" },
      icon: "capita",
      format: "decimal",
      select: { Үзүүлэлт: ["0"], ДНБ: ["0"] },
    },
    {
      id: "perCapitaUsd",
      file: "DT_NSO_0500_010V1.px",
      label: { mn: "Нэг хүнд ногдох ДНБ", en: "GDP per capita" },
      unit: { mn: "$", en: "$" },
      icon: "fx",
      format: "decimal",
      select: { Үзүүлэлт: ["0"], ДНБ: ["1"] },
    },
    {
      id: "useShare",
      file: "DT_NSO_0500_003V1_annual.px",
      label: { mn: "ДНБ, эцсийн ашиглалтаар", en: "GDP by final use" },
      format: "percent",
      select: { Үзүүлэлт: ["6"], Бүрэлдэхүүн: ["2", "3", "5", "7"] },
    },
    {
      id: "share",
      file: "DT_NSO_0500_002V1.px",
      label: { mn: "ДНБ-ий салбарын бүтэц", en: "GDP by industry" },
      format: "percent",
    },
    {
      id: "perCapitaMap",
      file: "DT_NSO_0500_011V1.px",
      geo: "Бүс",
      label: { mn: "Нэг хүнд ногдох ДНБ", en: "GDP per capita" },
      unit: { mn: "мян. ₮", en: "thousand ₮" },
      format: "currency",
    },
  ],
  widgets: [
    { type: "kpis", tables: ["gdp", "growth", "perCapita", "perCapitaUsd"] },
    {
      type: "category-stats",
      table: "useShare",
      dimension: "Бүрэлдэхүүн",
      labelMap: USE_LABELS,
      title: { mn: "ДНБ, эцсийн ашиглалтаар", en: "GDP by expenditure" },
    },
    {
      type: "category-bars",
      table: "share",
      dimension: "Салбар",
      layout: "horizontal",
      span: "full",
      top: 8,
      totals: ["Бүгд"],
      labelMap: SECTOR_LABELS,
      title: { mn: "ДНБ-ий бүтэц, салбараар", en: "GDP structure by industry" },
    },
    { type: "trend", tables: ["growth"], yAxis: "nice", title: { mn: "Эдийн засгийн өсөлт", en: "Economic growth" } },
    {
      type: "region-map",
      table: "perCapitaMap",
      layout: { legend: "horizontal" },
    },
  ],
};
