import "../globals.scss";
import "primeflex/primeflex.css";
import 'primeicons/primeicons.css';
import AdminLayout from '@/components/admin/layouts/AdminLayout';

import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children }) {
  return (
    <html lang="en">
      <body>
        <AdminLayout>
          {children}
        </AdminLayout>
      </body>
    </html>
  )
}
