"use client";

import { Suspense } from "react";
import Path from '@/components/path/Index';
import { useTranslation } from '@/app/i18n/client';

export default function Statecate({ children, params }) {
  const { lng } = params;
  const { t } = useTranslation(lng, "lng", "");

  const breadMap = [
    { label: t('home'), url: [lng === 'mn' ? '/mn' : '/en'] },
    { label: 'Хэрэглэгч үүсгэх' },
  ];

  return (
    <div className='nso_page_wrap'>
      <Path params={params} name={'Хэрэглэгч үүсгэх'} breadMap={breadMap} />
      <Suspense>
        {children}
      </Suspense>
    </div>
  );
}


// import { Suspense } from "react";

// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <head>
//         <title>Статистикийн мэдээллийн нэгдсэн сан</title>
//       </head>

//       <body>
//         <div className={` container max-w-lg mx-auto`}>
//           <main>
//             <Suspense>
//               <div> {children}</div>
//             </Suspense>
//           </main>
//         </div>
//       </body>
//     </html>
//   );
// }
