import { Inter } from "next/font/google";
import "./globals.scss";
import Layout from '@/components/baseLayout';
import Providers from "@/utils/providers/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { lng } }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Layout lng={lng}>
            {children}
          </Layout>
        </Providers>
      </body>
    </html>
  );
}
